### ISSUE TITLE
ラベルに「いちれんシャッフルのあり方」というのを作る

### ISSUE THREAD

**Issue by takuan-oishii** [ichiren1/ichiren1.github.io#10]
いちれんシャッフルのあり方の議論には必要でしょう

**Comment by ichiren1** [comment]
私もそう思います
![image](https://cloud.githubusercontent.com/assets/4242885/5833985/2c9729f8-a19c-11e4-8e4b-519f7d8f74fc.png)

追加しましたのでご確認ご確認ください

**Comment by takuan-oishii** [comment]
いいねそれ

**Comment by ichiren1** [comment]
クローズしまーす
