### ISSUE TITLE
一つから選んでTweetする時に候補が多いとTweetできない

### ISSUE THREAD

**Issue by satoshicano** [ichiren1/ichiren1.github.io#12]
試しに"poj"でテンプレにセットして一つから選び、Tweetしようとすると下図のように文字数が制限を超過する
![image](https://cloud.githubusercontent.com/assets/7578069/6096618/cb1f082a-afde-11e4-92f5-6a6035ca412f.png)

**Comment by ichiren1** [comment]
直したのでクローズします　ありがとうございました
