### ISSUE TITLE
右上にリポジトリへのリンクつける

### ISSUE THREAD

**Issue by takuan-oishii** [ichiren1/ichiren1.github.io#18]
ギッハブで開発してるソフトの公式サイトの右上に斜めの文字でFork me on githubみたいなの書いてあるじゃん。あれ。

**Comment by satoshicano** [comment]
![2015-05-03 20 18 54](https://cloud.githubusercontent.com/assets/7578069/7444833/aabdec24-f1d1-11e4-819a-d8d4645a7d9d.png)
こういうやつですね

**Comment by takuan-oishii** [comment]
それ

**Comment by ichiren1** [comment]
前あったんですけど消しました(^_^;)

**Comment by takuan-oishii** [comment]
え、なんで、新機能思いついた時すぐにcontributeできないじゃん。

**Comment by ichiren1** [comment]
なるほど

**Comment by takuan-oishii** [comment]
うん

**Comment by ichiren1** [comment]
左上に付けました　すいません

ありがとうございました　クローズします
