### ISSUE TITLE
シャッフルできなくないですか

### ISSUE THREAD

**Issue by takuan-oishii** [ichiren1/ichiren1.github.io#22]
あの,マテリアルデザインになってからボタン押しても何も起きなかったりとかsafariでガタガタになったりとかGitHubへのリンクがyouとかいうユーザになってたりとかちょっとガバガバすぎませんか.
弊社でいちれんシャッフル使えなくなっちゃうからシャッフルできるようにしてくれ頼む.

**Comment by satoshicano** [comment]
Chromeでもシャッフルできませんね
環境は
- Mac OS X 10.10.3
- Google Chrome 42.0.2311.135 (64-bit)
です

**Comment by ichiren1** [comment]
http://ichiren1.github.io/before.html 使っててください

**Comment by takuan-oishii** [comment]
ウケる

**Comment by ichiren1** [comment]
直したのでクローズします
ありがとうございました
