### ISSUE TITLE
未対応ブラウザーをどうするか

### ISSUE THREAD

**Issue by mizukmb** [ichiren1/ichiren1.github.io#26]
![2015-05-21](https://cloud.githubusercontent.com/assets/7896080/7747782/df06c4c6-fff8-11e4-9f52-668d87026e37.png)

https://www.polymer-project.org/0.5/resources/compatibility.html

解決策として[before.html](https://github.com/ichiren1/ichiren1.github.io/blob/master/before.html)にリダイレクトさせるというのはどうでしょうか

**Comment by ichiren1** [comment]
現状、それが一番手っ取り早くて確実かも　
後々本腰入れて作るまでそれが良さそう

**Comment by mizukmb** [comment]
こうした問題が発生の原因はいちれんシャッフルではなく、Web Components という最新テクノロジーをサポートしていない各ブラウザーが悪いのです。
