### ISSUE TITLE
リポジトリが変わったことを知らせる

### ISSUE THREAD

**Issue by satoshicano** [ichiren1/ichiren1.github.io#48]
[ichiren1/useful-shuffle](https://github.com/ichiren1/useful-shuffle)に移行したことを`README.md`にかきたい

**Comment by mizukmb** [comment]
ping

**Comment by ichiren1** [comment]
https://github.com/ichiren1/useful-shuffle

**Comment by satoshicano** [comment]
優勝！

**Comment by mizukmb** [comment]
R.I.P
