### ISSUE TITLE
グループ機能がほしい

### ISSUE THREAD

**Issue by yuuto1012227** [ichiren1/ichiren1.github.io#7]
例）
1. A
2.  B
3.  C
4. D
5. E
6.  F
7.  G
8.  H

をシャッフルした時、

### GROUP1
1. A
- C
- E
- G

### GROUP2
1. B
- D
- F
- H

みたいな感じ
グループ数も決められると嬉しい

**Comment by ichiren1** [comment]
左側入力出来るじゃないですか
そこにGROUP１とGROUP２を書けば再現可能だと思います
